### ISSUE TITLE
Will this block a logged in user from entering a contribution on a public page? 

### ISSUE THREAD

**Issue by joemcl** [TechToThePeople/noverwrite#8]
No an issue, but a question. 

I like what this extension is supposed to do. I'm installing it on our staging site to test. 

My most common problem is registered users who are signed in and use a public membership contribution page to enter another person's info for a membership contribution. I have tried coaching users who want to do this to use an incognito page, which works when they do it correctly. But not all users do this consistently. 

Because the extension makes the signed-in user's first name and last name read-only, will it block a user from entering the other person's contribution info - credit card, billing address, etc - on a page like this - https://my.citizenactionny.org/civicrm/contribute/transact?reset=1&id=2 

Thanks!

**Comment by tttp** [comment]
Hey,

If that extension didn't block it, they would update their own contact
details with the donor name, so that's rather a good thing IMO.

Don't you have a message "you are here as John doe, if not john doe click
here?" from the top of my head, there is an option somewhere in the contrib
page to add that warning

X+

**Comment by joemcl** [comment]
Thanks, yeah the warning message is turned on for the page(s). Checking out the extension.
